<expr>  ::= (<expr> + <expr>)
        | (<expr> - <expr>)
        | (<expr> * <expr>)
        | GT(<expr>, <expr>)
        | DIV(<expr>, <expr>)
        | ABS(<expr>)
        | X
        | V
        | (-1.0)
