<expr>	::=	(<expr> <op> <expr>)
		| <u-pre-op>(<expr>)
		| <b-pre-op>(<expr>,<expr>)
		| <var>
<op>	::=	+ | - | * | /
<u-pre-op>	::=	ABS| sin | cos | exp | log
<b-pre-op>	::=	DIV
			| GT | LT
<var>	::=	X | V | (-1.0)
