<expr>	::=	(<expr> <op> <expr>)
		| <u-pre-op>(<expr>)
		| <b-pre-op>(<expr>,<expr>)
		| <var>
		| <const>
<op>	::=	+ | - | .* 
<u-pre-op>	::=	ge_exp | ge_log | ge_log10 
<b-pre-op>	::=	ge_divide | ge_power
<var>	::=	X(:,1) | X(:,2) | X(:,3) | X(:,4) | X(:,5) | X(:,6) | X(:,7) | X(:,8) | X(:,9) | X(:,10) | X(:,11) | X(:,12) | X(:,13) | X(:,14) | X(:,15) | X(:,16) | X(:,17) | X(:,18) | X(:,19) | X(:,20) | X(:,21) | X(:,22) | X(:,23) | X(:,24) | X(:,25) | X(:,26) | X(:,27) | X(:,28) | X(:,29) | X(:,30) | X(:,31) | X(:,32) | X(:,33) | X(:,34) | X(:,35) | X(:,36) | X(:,37) | X(:,38) | X(:,39) | X(:,40) | X(:,41) | X(:,42) | X(:,43) | X(:,44) | X(:,45) | X(:,46) | X(:,47) | X(:,48) | X(:,49) | X(:,50) | X(:,51) | X(:,52) | X(:,53) | X(:,54) | X(:,55) | X(:,56) | X(:,57)
<const>	::=	w(1) | w(2) | w(3) | w(4) | w(5)

