<expr>	::=	<lexpr><op><expr> <pop>
        |   <u-pre-op>(<expr>)  <pop>
        |   <b-pre-op>(<expr>, <expr>) <pop>
		| <var>
		| <const>
<lexpr> ::= <expr>
<op>    ::= + | - | .*
<u-pre-op>  ::= ge_sin | ge_cos | ge_log | ge_log10 | ge_log2 | ge_tanh | ge_sigmoid | ge_sqrt | ge_square | ge_cube | ge_quart | ge_tan | ge_exp
<b-pre-op>  ::= ge_power | ge_divide | ge_scaledsigmoid
<var>	::=	X(:,1)
<const>	::=	w(1)
<pop>   ::= ""