<expr>	::=	(<expr> <op> <expr>)
		| <u-pre-op>(<expr>)
		| <b-pre-op>(<expr>,<expr>)
		| <var>
		| <const>
<op>	::=	+ | - | .* 
<u-pre-op>	::=	ge_sin | ge_cos| ge_sqrt | ge_log | ge_log2 | ge_log10 | ge_square | ge_tan | ge_tanh | ge_exp | ge_cube | ge_quart
<b-pre-op>	::=	ge_divide
<var>	::=	X(:,1) 
<const>	::=	w(1) 
